name: build image
on:
  push:
    branches: [ "main" ] # main 브랜치 merge 트리거 되었을 경우

env:
  REGISTRY: ghcr.io # 깃허브 컨테이너 저장소를 사용한다.
  IMAGE_NAME: yonggyo1125/gateway-server
  VERSION: latest

jobs:
  ImageBuild:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    environment: deploy
    steps:
      - name: Checkout source code # 소스코드 체크 아웃
        uses: actions/checkout@v4

      - name: Set up JDK # JDK 지정
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Build container image # 도커 이미지 생성
        run: |
          IMAGE=$REGISTRY/$IMAGE_NAME:$VERSION
           chmod +x gradlew
           ./gradlew bootJar
           docker build -t $IMAGE .
           echo "IMAGE_URI=$IMAGE" >> $GITHUB_ENV

      - name: Log into container registry # 깃허브 이미지 컨테이너 로그인 및 push
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish container image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
